---
- name: Разворачивание Prometheus и стека логирования EFK
  hosts: all
  become: true
  vars:
    opensearch_version: "2.9.0"
    opensearch_dashboards_version: "2.9.0"
    prometheus_version: "2.45.0"
    node_exporter_version: "1.6.0"
    fluentbit_version: "2.1.0"
  roles:
    - role: prometheus
      tags: ["prometheus"]
    - role: node_exporter
      tags: ["node_exporter"]
    - role: opensearch
      tags: ["opensearch"]
    - role: fluentbit
      tags: ["fluentbit"]
