---
- name: Создание пользователя и группы Node Exporter
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    system: true
    shell: /sbin/nologin
    create_home: false

- name: Загрузка и установка Node Exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Копирование бинарника Node Exporter
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_bin }}"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes

- name: Копирование systemd unit файла
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Node Exporter

- name: Запуск и включение Node Exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes
