- name: Создание пользователя и группы Prometheus
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    system: true
    shell: /sbin/nologin
    create_home: false
    home: "{{ prometheus_home }}"

- name: Создание необходимых директорий
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
  loop:
    - "{{ prometheus_home }}"
    - "{{ prometheus_data_dir }}"

- name: Загрузка и установка Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Копирование бинарников
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Копирование конфига Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: Restart Prometheus

- name: Добавление Node Exporter в конфиг Prometheus
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_file }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: Restart Prometheus

- name: Копирование systemd unit файла
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Prometheus

- name: Запуск и включение Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
    daemon_reload: yes
